
COLUMN_MAPPING = {
    "Kepler": {
        "id":"kepid",
        "period": "koi_period",
        "duration": "koi_duration",
        "depth": "koi_depth",
        "steff": "koi_steff",
        "srad": "koi_srad",
        "slogg": "koi_slogg",
        "model_snr": "koi_model_snr",
        "ra": "ra",
        "dec": "dec",
        "disposition": "koi_disposition"
    },
    "TESS": {
        "id":"toi",
        "period": "pl_orbper",
        "duration": "pl_trandurh",
        "depth": "pl_trandep",
        "steff": "st_teff",
        "srad": "st_rad",
        "slogg": "st_logg",
        "model_snr": "pl_eqt", 
        "ra": "ra",
        "dec": "dec",
        "disposition": "tfopwg_disp"
    }
}

kepler_columns = ['rowid', 'kepid', 'kepoi_name', 'kepler_name', 
                  'koi_disposition', 'koi_vet_stat', 'koi_vet_date', 
                  'koi_pdisposition', 'koi_score', 
                  'koi_fpflag_nt', 'koi_fpflag_ss', 'koi_fpflag_co', 'koi_fpflag_ec', 
                  'koi_disp_prov', 'koi_comment', 
                  'koi_period', 'koi_period_err1','koi_period_err2', 
                  'koi_time0bk', 'koi_time0bk_err1', 'koi_time0bk_err2', 
                  'koi_time0', 'koi_time0_err1', 'koi_time0_err2', 
                  'koi_eccen', 'koi_eccen_err1', 'koi_eccen_err2', 
                  'koi_longp', 'koi_longp_err1', 'koi_longp_err2', 
                  'koi_impact', 'koi_impact_err1', 'koi_impact_err2', 
                  'koi_duration', 'koi_duration_err1', 'koi_duration_err2', 
                  'koi_ingress', 'koi_ingress_err1', 'koi_ingress_err2', 
                  'koi_depth', 'koi_depth_err1', 'koi_depth_err2', 
                  'koi_ror', 'koi_ror_err1', 'koi_ror_err2', 
                  'koi_srho', 'koi_srho_err1', 'koi_srho_err2', 
                  'koi_fittype', 
                  'koi_prad', 'koi_prad_err1', 'koi_prad_err2', 
                  'koi_sma', 'koi_sma_err1', 'koi_sma_err2', 
                  'koi_incl', 'koi_incl_err1', 'koi_incl_err2', 
                  'koi_teq', 'koi_teq_err1', 'koi_teq_err2', 
                  'koi_insol', 'koi_insol_err1', 'koi_insol_err2', 
                  'koi_dor', 'koi_dor_err1', 'koi_dor_err2', 
                  'koi_limbdark_mod', 'koi_ldm_coeff4', 'koi_ldm_coeff3', 'koi_ldm_coeff2', 'koi_ldm_coeff1', 
                  'koi_parm_prov', 'koi_max_sngle_ev', 'koi_max_mult_ev', 'koi_model_snr', 'koi_count', 
                  'koi_num_transits', 'koi_tce_plnt_num', 'koi_tce_delivname', 'koi_quarters', 'koi_bin_oedp_sig', 
                  'koi_trans_mod', 'koi_model_dof', 'koi_model_chisq', 'koi_datalink_dvr', 'koi_datalink_dvs', 
                  'koi_steff', 'koi_steff_err1', 'koi_steff_err2', 
                  'koi_slogg', 'koi_slogg_err1', 'koi_slogg_err2', 
                  'koi_smet', 'koi_smet_err1', 'koi_smet_err2', 
                  'koi_srad', 'koi_srad_err1', 'koi_srad_err2', 
                  'koi_smass', 'koi_smass_err1', 'koi_smass_err2', 
                  'koi_sage', 'koi_sage_err1', 'koi_sage_err2', 
                  'koi_sparprov', 'ra', 'dec', 'koi_kepmag', 
                  'koi_gmag', 'koi_rmag', 'koi_imag', 'koi_zmag', 'koi_jmag', 'koi_hmag', 'koi_kmag', 'koi_fwm_stat_sig', 'koi_fwm_sra', 'koi_fwm_sra_err', 
                  'koi_fwm_sdec', 'koi_fwm_sdec_err', 'koi_fwm_srao', 'koi_fwm_srao_err', 'koi_fwm_sdeco', 'koi_fwm_sdeco_err', 'koi_fwm_prao', 'koi_fwm_prao_err', 
                  'koi_fwm_pdeco', 'koi_fwm_pdeco_err', 'koi_dicco_mra', 'koi_dicco_mra_err', 'koi_dicco_mdec', 'koi_dicco_mdec_err', 'koi_dicco_msky', 
                  'koi_dicco_msky_err', 'koi_dikco_mra', 'koi_dikco_mra_err', 'koi_dikco_mdec', 'koi_dikco_mdec_err', 'koi_dikco_msky', 'koi_dikco_msky_err']

tess_columns = ['rowid', 'toi', 'toipfx', 'tid', 'ctoi_alias', 'pl_pnum', 'tfopwg_disp', 'rastr', 'ra', 'raerr1', 'raerr2', 'decstr', 'dec', 'decerr1', 'decerr2', 
                'st_pmra', 'st_pmraerr1', 'st_pmraerr2', 'st_pmralim', 'st_pmrasymerr', 'st_pmdec', 'st_pmdecerr1', 'st_pmdecerr2', 'st_pmdeclim', 'st_pmdecsymerr', 
                'pl_tranmid', 'pl_tranmiderr1', 'pl_tranmiderr2', 'pl_tranmidlim', 'pl_tranmidsymerr', 'pl_orbper', 'pl_orbpererr1', 'pl_orbpererr2', 'pl_orbperlim', 
                'pl_orbpersymerr', 'pl_trandurh', 'pl_trandurherr1', 'pl_trandurherr2', 'pl_trandurhlim', 'pl_trandurhsymerr', 'pl_trandep', 'pl_trandeperr1', 
                'pl_trandeperr2', 'pl_trandeplim', 'pl_trandepsymerr', 'pl_rade', 'pl_radeerr1', 'pl_radeerr2', 'pl_radelim', 'pl_radesymerr', 'pl_insol', 'pl_insolerr1', 
                'pl_insolerr2', 'pl_insollim', 'pl_insolsymerr', 'pl_eqt', 'pl_eqterr1', 'pl_eqterr2', 'pl_eqtlim', 'pl_eqtsymerr', 'st_tmag', 'st_tmagerr1', 'st_tmagerr2', 
                'st_tmaglim', 'st_tmagsymerr', 'st_dist', 'st_disterr1', 'st_disterr2', 'st_distlim', 'st_distsymerr', 'st_teff', 'st_tefferr1', 'st_tefferr2', 'st_tefflim', 
                'st_teffsymerr', 'st_logg', 'st_loggerr1', 'st_loggerr2', 'st_logglim', 'st_loggsymerr', 'st_rad', 'st_raderr1', 
                'st_raderr2', 'st_radlim', 'st_radsymerr', 'toi_created', 'rowupdate']